name: Check Latest Release

on:
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: cgwire
          repo: kitsu
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
