name: Check Latest Release

on:
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: cgwire
          repo: kitsu
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: All data
        run: "echo data: '${{ steps.get_latest_release.outputs.data }}'"

      - name: Extract tag_name from JSON response
        run: |
          # Extract tag_name using jq and store it in an environment variable
          export TAG_NAME=$(echo ${{ steps.get_latest_release.outputs.data }} | jq -r 'tag_name')

          # Print the tag_name for verification
          echo "tag_name: $TAG_NAME"
